/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team2.courseManagement;

import edu.duke.ece651.team2.server.DAOFactory;
import edu.duke.ece651.team2.server.UniversityDAO;
import edu.duke.ece651.team2.shared.University;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.checkerframework.checker.units.qual.C;

import java.util.List;

public class App extends Application {

    private List<University> universityNames() {
        DAOFactory daoFactory = new DAOFactory();
        UniversityDAO uniDAO = new UniversityDAO(daoFactory);
        return uniDAO.list();
    }

    @Override
    public void start(Stage stage) throws Exception {
        LoginController login = new LoginController(universityNames());
        stage.setScene(new Scene(login));
        stage.setWidth(600);
        stage.setHeight(500);
        stage.show();
    }
}
