/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team2.courseManagement;

import edu.duke.ece651.team2.shared.University;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {

    private final CourseManagementController controller;

    public App(CourseManagementController controller) {
        this.controller = controller;
    }

    public static void main(String[] args) throws IOException {
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        SelectUniversity select = new SelectUniversity(System.out, input);
        University university = select.readUniversity();
        CourseManagement model = new CourseManagement(university);
        CourseManagementController controller = new CourseManagementController(model, System.out, input);

        App app = new App(controller);
        app.run();
    }

    public void run() throws IOException {
        while(!controller.isShouldExit()) {
            try {
                controller.chooseOption();
            } catch (IllegalArgumentException e) {
                controller.invalidSelection();
            }
        }
    }
}
