/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team2.server;

import java.io.*;
import java.net.*;

public class App {
  private ServerSideView serverSideView;
  private ServerSideController serverSideController;
  private ServerSocket serverSocket;

  public App() {
    serverSideView = new ServerSideView();
  }

  public void connectToClients() throws ClassNotFoundException {
    try {
      serverSocket = new ServerSocket(8088);
      serverSideView.displayMessage("Server started, waiting for client connections...");

      while (true) {
        Socket clientSocket = serverSocket.accept();
        serverSideController = new ServerSideController(serverSideView);
        serverSideView.displayMessage("Client connected");

        // Send connection status to client
        serverSideController.sendConnectionStatus(clientSocket);

        // Handle login
        while(serverSideController.getStatus()==-1){
          serverSideController.handleLogin(clientSocket);
        }

        // Create a new thread to handle client requests
        ClientHandler clientHandler = new ClientHandler(clientSocket, serverSideView, serverSideController);
        new Thread(clientHandler).start();
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  public static void main(String[] args) throws ClassNotFoundException {
    App a = new App();
    a.connectToClients();
  }

}
