/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team2.client;

import edu.duke.ece651.team2.shared.Password;
import java.io.*;
import java.net.*;
import java.util.List;

public class App {

  private ClientSideController clientSideController;
  private ClientSideView clientSideView;
  private ObjectInputStream in;
  private ObjectOutputStream out;
  private Socket socket;
  private boolean connected = false;

  public App() {
    clientSideView = new ClientSideView();
    clientSideController = new ClientSideController(clientSideView);
  }

  public String[] parseMessage(String receivedMessage, String delimiter) {
    return receivedMessage.split(delimiter);
  }

  private int login() throws ClassNotFoundException {
    boolean loginSuccess = false;
    int userType = 0;

    while (!loginSuccess) {
      try {
        String[] credentials = clientSideController.login();
        int userID = Integer.parseInt(credentials[0]);
        Password input = new Password(userID, credentials[1]);
        out.writeObject(input); // Send userID & password to server (default send Password object)
        out.flush(); // Flush the stream to ensure data is sent immediately

        // Read login result from server (By default, a string object is sent back.Click
        // to apply)
        String[] response = parseMessage((String) in.readObject(), ":");
        String choice = response[0];
        String prompt = response[1];
        if (choice.equals("1")) {
          userType = 1; // student
          // clientSideView.displayMessage("Login successful.");
          loginSuccess = true;
        } else if (choice.equals("2")) {
          userType = 2; // Faculty
          loginSuccess = true;
          // clientSideView.displayMessage("Login successful.");
        } else {
          clientSideView.displayMessage(prompt);
          clientSideView.displayMessage("Login failed. Please try again.");
        }
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
    return userType;
  }

  // Student-specific functionality
  private void studentFunctionality() {
    while (true) {
      try {
        int choice = clientSideController.studentOperations();
        if (choice == 3) {
          // exit
          disconnectFromServer();
          break;
        } else if (choice == 1) {
          // send to server
          out.writeInt(choice); // int type
          out.flush();
          setEmailPreferences();
        } else if (choice == 2) {
          // send to server
          out.writeInt(choice);
          out.flush();
          getAttendanceReport();
        }

      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }

  private void receiveAllEnrolledSectionAndSetChoice(int num) {
    clientSideView.displayMessage(
        "Below are all the courses you are enrolled in this semester, please select one to set your email preferences.");
    try {
      // get from server
      Object response = in.readObject();
      if (response instanceof List) {
        List<String> responseList = (List<String>) response;
        int len = responseList.size();
        int resNum = -1;
        while (true) {
          String choice = clientSideController.joinEnrolledSectionPreference(responseList);
          if (clientSideController.isValidIntegerInRange(choice, 1, len)) {
            resNum = Integer.parseInt(choice);
            break;
          } else {
            clientSideView.displayMessage("Please enter a valid number!");
          }
        }
        out.writeObject(resNum); // send int type
        if (num == 1) {
          changeEmailPreferences();
        } else {
          receiveReportResult();
        }

      } else if (response instanceof List) {
        String errorMessage = (String) response;
        clientSideView.displayMessage("An error occurred on the server: " + errorMessage);
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  // 1. set email preferences
  private void setEmailPreferences() {
    receiveAllEnrolledSectionAndSetChoice(1);
  }

  private void confirmFromServer() {
    try {
      Object response = in.readObject();
      if (response instanceof String) {
        String responseStr = (String) response;
        String[] parts = responseStr.split("\\|\\|");
        String stateCode = parts[0]; // 0/1 0 - error, 1 - success
        String prompt = parts[1];
        if (stateCode.equals("0")) {
          clientSideView.displayMessage(prompt);
        } else {
          // success
          clientSideView.displayMessage(prompt);
        }
      } else {
        clientSideView.displayMessage("Server failed to send a message!");
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private void changeEmailPreferences() {
    clientSideView.displayMessage("Check Course Subscription Status...");
    try {
      // get from server
      Object response = in.readObject();
      if (response instanceof String) {
        String responseStr = (String) response;
        String[] parts = responseStr.split("\\|\\|");
        String stateCode = parts[0]; // 0/1 0 - error, 1 - success
        String prompt = parts[1];
        if (stateCode.equals("0")) {
          clientSideView.displayMessage(prompt);
        } else if (stateCode.equals("1")) {
          int resNum = -1;
          while (true) {
            String choice = clientSideView.promptUser(prompt);
            if (clientSideController.isValidIntegerInRange(choice, 0, 1)) {
              resNum = Integer.parseInt(choice);
              break;
            } else {
              clientSideView.displayMessage("Please enter a valid number!");
            }
          }
          // client asked to change status
          if (resNum == 1) {
            out.writeObject(resNum);
            out.flush();
            // receive msg from server
            confirmFromServer();
          }
        } else {
          clientSideView.displayMessage("Error request!");
        }
      } else {
        clientSideView.displayMessage("Server failed to send a message!");
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  // 2. get attendance report for a course
  private void getAttendanceReport() {
    receiveAllEnrolledSectionAndSetChoice(2);
  }

  private void receiveReportResult() {
    clientSideView.displayMessage("Pending report...");
    confirmFromServer();
  }

  // Professor-specific functionality
  private void professorFunctionality() {
    while (true) {
      try {
        int choice = clientSideController.professorOperations();
        if (choice == 5) {
          // exit
          disconnectFromServer();
          break;
        }
        // send to server
        out.writeInt(choice); // int type
        out.flush();
        if (choice == 1) {

        } else if (choice == 2) {

        } else if (choice == 3) {

        } else if (choice == 4) {

        }

      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }

  public void start() throws ClassNotFoundException {
    boolean connected = connectToServer();
    if (connected) {
      int userType = login();
      if (userType == 1) {
        clientSideView.displayMessage("Student login successful.");
        studentFunctionality();
      } else if (userType == 2) {
        professorFunctionality();
        clientSideView.displayMessage("Faculty login successful.");
      } else {
        clientSideView.displayMessage("Unknown user type.");
      }
    }
  }

  private boolean connectToServer() throws ClassNotFoundException {

    while (!connected) {
      try {
        // Connect to the server
        socket = new Socket("localhost", 8088);
        // in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        // out = new PrintWriter(socket.getOutputStream(), true);
        out = new ObjectOutputStream(socket.getOutputStream());
        in = new ObjectInputStream(socket.getInputStream());

        // Read connection status from server
        int connectionStatus = (int) in.readObject(); // int type
        if (connectionStatus == 1) {
          clientSideView.displayMessage("Connected to server.");
          connected = true;
        } else {
          clientSideView.displayMessage("Failed to connect to server.");
          clientSideView.displayMessage("Trying to connect again...");
          try {
            Thread.sleep(2000); // Wait for 2 seconds before retrying
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
        }

      } catch (IOException e) {
        e.printStackTrace();
      }
    }

    return connected;
  }

  public static void main(String[] args) throws ClassNotFoundException {
    App a = new App();
    a.start();
  }

  // Disconnect from the server
  public void disconnectFromServer() {
    try {
      if (socket != null && !socket.isClosed()) {
        socket.close();
        connected = false;
        clientSideView.displayMessage("Disconnected from the server.");
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}